title: <p align="center"> Tadashi Mori </p>

logo: "/images/perfil_redondo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/tadashi-mori/">LinkedIn</a> |
  <a href="https://github.com/tadashiorigami">GitHub</a>
  </p>
  
  <p align="justify">
  I am Mathematician, graduated in University of São Paulo.
  <br><br>
  I am currently working as a Data Scientist freelancer.
  <br><br>
  </p>
